### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by rahulkathet** [Abhivbk/CoWin-KYC-VS#1]
This is publicly not available.

**Comment by Abhivbk** [comment]
Yes, sorry for that but for the first two months it was available but after that the government did not give the permission to use the API key. If you have any way to get the API key you can use it. Now the api is just for registered officials.

**Comment by rahulkathet** [comment]
Yes

**Comment by Abhivbk** [comment]
@rahulkathet have you found any way to get the permission for the protected APIs [https://apisetu.gov.in/api/cowin/cowin-protected-v2#/](url). This project is very important for me. If you have any way please help.

**Comment by rahulkathet** [comment]
> @rahulkathet have you found any way to get the permission for the protected APIs [https://apisetu.gov.in/api/cowin/cowin-protected-v2#/](url). This project is very important for me. If you have any way please help.

Sure.
